// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef PROTOBUF_game_2eproto__INCLUDED
#define PROTOBUF_game_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pang {
namespace config {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_game_2eproto();
void protobuf_AssignDesc_game_2eproto();
void protobuf_ShutdownFile_game_2eproto();

class Game;

// ===================================================================

class Game : public ::google::protobuf::Message {
 public:
  Game();
  virtual ~Game();

  Game(const Game& from);

  inline Game& operator=(const Game& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Game& default_instance();

  void Swap(Game* other);

  // implements Message ----------------------------------------------

  Game* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Game& from);
  void MergeFrom(const Game& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 width = 1;
  inline bool has_width() const;
  inline void clear_width();
  static const int kWidthFieldNumber = 1;
  inline ::google::protobuf::int32 width() const;
  inline void set_width(::google::protobuf::int32 value);

  // optional int32 height = 2;
  inline bool has_height() const;
  inline void clear_height();
  static const int kHeightFieldNumber = 2;
  inline ::google::protobuf::int32 height() const;
  inline void set_height(::google::protobuf::int32 value);

  // optional int32 num_enemies = 3;
  inline bool has_num_enemies() const;
  inline void clear_num_enemies();
  static const int kNumEnemiesFieldNumber = 3;
  inline ::google::protobuf::int32 num_enemies() const;
  inline void set_num_enemies(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pang.config.Game)
 private:
  inline void set_has_width();
  inline void clear_has_width();
  inline void set_has_height();
  inline void clear_has_height();
  inline void set_has_num_enemies();
  inline void clear_has_num_enemies();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 num_enemies_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_game_2eproto();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
  static Game* default_instance_;
};
// ===================================================================


// ===================================================================

// Game

// optional int32 width = 1;
inline bool Game::has_width() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Game::set_has_width() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Game::clear_has_width() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Game::clear_width() {
  width_ = 0;
  clear_has_width();
}
inline ::google::protobuf::int32 Game::width() const {
  return width_;
}
inline void Game::set_width(::google::protobuf::int32 value) {
  set_has_width();
  width_ = value;
}

// optional int32 height = 2;
inline bool Game::has_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Game::set_has_height() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Game::clear_has_height() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Game::clear_height() {
  height_ = 0;
  clear_has_height();
}
inline ::google::protobuf::int32 Game::height() const {
  return height_;
}
inline void Game::set_height(::google::protobuf::int32 value) {
  set_has_height();
  height_ = value;
}

// optional int32 num_enemies = 3;
inline bool Game::has_num_enemies() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Game::set_has_num_enemies() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Game::clear_has_num_enemies() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Game::clear_num_enemies() {
  num_enemies_ = 0;
  clear_has_num_enemies();
}
inline ::google::protobuf::int32 Game::num_enemies() const {
  return num_enemies_;
}
inline void Game::set_num_enemies(::google::protobuf::int32 value) {
  set_has_num_enemies();
  num_enemies_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace config
}  // namespace pang

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_2eproto__INCLUDED
